language: python
dist: xenial
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8-dev
    - pypy
    - pypy3
matrix:
    include:
        - name: "2.7-pure"
          python: "2.7"
          env: PURE_PYTHON=1
        - name: "3.7-pure"
          python: "3.7"
          env: PURE_PYTHON=1
install:
    - pip install zc.buildout
    - pip install coveralls coverage
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test -v1
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
