language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: "3.7"
          dist: xenial
install:
    - pip install six==1.10.0 # force to avoid conflict with zc.recipe.testrunner
    - pip install zc.buildout
    - pip install coveralls coverage
    - buildout bootstrap
    - buildout
script:
    - coverage run bin/test -v1
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
